apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-configmap
  labels:
    app: keystone
data:
  keystone.conf: |-
    [database]
    connection = {{ include "keystone.databaseUri" .}}

    [token]
    provider = fernet