apiVersion: v1
kind: Service
metadata:
  name: {{ include "keystone.fullname" . }}
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "keystone.selectorLabels" . | nindent 4 }}
